const menuButton=document.querySelector('.menu-toggle');
const menu=document.querySelector('.main-nav');
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menu.classList.toggle('open',open);});
const dropButton=document.querySelector('.drop-toggle');
dropButton?.addEventListener('click',()=>{const open=dropButton.getAttribute('aria-expanded')!=='true';dropButton.setAttribute('aria-expanded',String(open));dropButton.closest('.nav-service').classList.toggle('open',open);});
document.addEventListener('click',e=>{if(!e.target.closest('.nav-service')){dropButton?.setAttribute('aria-expanded','false');document.querySelector('.nav-service')?.classList.remove('open');}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const menuOpen=menu?.classList.contains('open');const dropOpen=dropButton?.getAttribute('aria-expanded')==='true';menu?.classList.remove('open');menuButton?.setAttribute('aria-expanded','false');dropButton?.setAttribute('aria-expanded','false');document.querySelector('.nav-service')?.classList.remove('open');if(menuOpen)menuButton.focus();else if(dropOpen)dropButton.focus();}});
document.querySelectorAll('.compare input').forEach(input=>{const update=()=>{input.closest('.compare').style.setProperty('--pos',input.value+'%');input.setAttribute('aria-valuetext',input.value+'% before image revealed');};input.addEventListener('input',update);update();});
document.querySelectorAll('[data-load-map]').forEach(button=>button.addEventListener('click',()=>{const panel=button.closest('.map-panel');const frame=document.createElement('iframe');frame.title='Map of Glasgow, Scotland';frame.src='https://maps.google.com/maps?q=Glasgow%2C%20Scotland&z=11&output=embed';frame.referrerPolicy='strict-origin-when-cross-origin';frame.allowFullscreen=true;panel.replaceChildren(frame);}));
const form=document.querySelector('#enquiry-form');
if(form){form.querySelector("fieldset").disabled=false;const select=form.querySelector('[name="service"]');const requested=new URLSearchParams(location.search).get('service');if(requested&&[...select.options].some(o=>o.value===requested))select.value=requested;form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const status=document.querySelector('#form-status');status.hidden=false;const name=form.elements.namedItem('name').value.trim().split(/\s+/)[0];status.querySelector('h3').textContent=`Thank you, ${name}. Your form preview is complete.`;status.querySelector('p').textContent='This is a test website. Your enquiry has not been sent, saved or booked. A live contact service needs to be connected before real bookings can be accepted.';status.focus();status.scrollIntoView({behavior:'smooth',block:'center'});});}
